// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkpRz_yh_zbLnyjornybsTHaOHo52nbyU',
    appId: '1:830586470712:web:597f8084185573933841cd',
    messagingSenderId: '830586470712',
    projectId: 'wiccastore3',
    authDomain: 'wiccastore3.firebaseapp.com',
    storageBucket: 'wiccastore3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDosOcAxSowC-QTbt6AOXCMzo7vrJZgmk',
    appId: '1:830586470712:android:87cf1975501976593841cd',
    messagingSenderId: '830586470712',
    projectId: 'wiccastore3',
    storageBucket: 'wiccastore3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOKVQLUL3PDkovMvBoacphJHfzWqBGjI',
    appId: '1:830586470712:ios:62a527dc3b9959e03841cd',
    messagingSenderId: '830586470712',
    projectId: 'wiccastore3',
    storageBucket: 'wiccastore3.appspot.com',
    iosBundleId: 'com.example.wiccaStore3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOKVQLUL3PDkovMvBoacphJHfzWqBGjI',
    appId: '1:830586470712:ios:d28e0985529b76f03841cd',
    messagingSenderId: '830586470712',
    projectId: 'wiccastore3',
    storageBucket: 'wiccastore3.appspot.com',
    iosBundleId: 'com.example.wiccaStore3.RunnerTests',
  );
}
